const pancards = [
  {
    id: 1,
    pancard_number: "AHPPP1323H",
    name: "TestName Test1",
    father_name: "TestFatherName Test1",
    date_of_birth: "1995-01-05",
    status: "Active",
    type: "Individual",
    credit_score: 800,
  },
  {
    id: 2,
    pancard_number: "BHPPP2323H",
    name: "TestName Test2",
    father_name: "TestFatherName Test2",
    date_of_birth: "2000-02-06",
    status: "Active",
    type: "Individual",
    credit_score: 700,
  },
  {
    id: 3,
    pancard_number: "CHPPP3323H",
    name: "TestName Test3",
    father_name: "TestFatherName Test3",
    date_of_birth: "2005-03-07",
    status: "Active",
    type: "Individual",
    credit_score: 600,
  },
  {
    id: 4,
    pancard_number: "DHPPP3323H",
    name: "TestName Test4",
    father_name: "TestFatherName Test4",
    date_of_birth: "2005-03-07",
    status: "Active",
    type: "Individual",
    credit_score: 500,
  },
  {
    id: 5,
    pancard_number: "EHPPP3323H",
    name: "TestName Test5",
    father_name: "TestFatherName Test5",
    date_of_birth: "2005-03-07",
    status: "InActive",
    type: "Individual",
    credit_score: 750,
  },
];

module.exports = {
  pancards,
};
